permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 5
comments: true
paginate_path: "/page/:num"

destination: _site
sass:
  sass_dir: _scss
  style: compressed

# cover: /assets/images/default-cover.png
cover: /assets/images/matrix-code.jpg

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Grande Portal
title: Grande Portal
description: "Blog sobre programação"
keywords: "bash, shell, terminal, python, django, linux"
url: http://grandeportal.github.io/
baseurl: ""
# domain_name: nandomoreira.me
# google_analytics: UA-52446115-1
repo: https://github.com/grandeportal/grandeportal.github.io
disqus_shortname: "rg3915"

author:
  name      : Régis da Silva Santos
  image     : /assets/images/author.jpg
  email     : regis.santos.100@gmail.com
  url       : http://grandeportal.github.io/
  twitter   : http://twitter.com/rg3915
  github    : http://github.com/rg3915

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
